### ISSUE TITLE
Support Thesaurus

### ISSUE THREAD

**Issue by alex-taxiera** [NdYAG/mw-dict#3]
Any plans to add "Merriam-Webster's Collegiate® Thesaurus" functionality?

**Comment by NdYAG** [comment]
Hi @alex-taxiera 
it could be supported but properly later
I'll mention you once it's implemented

**Comment by NdYAG** [comment]
Hi @alex-taxiera 
sorry for not responding earlier
https://github.com/NdYAG/mw-dict/commit/f5cc4d482b46dbe662c3d17b7c71471b9990472b

Collegiate® Thesaurus is now supported,
use case is basically same as Dictionary,
```js
import { CollegiateThesaurus } from 'mw-dict'
const thesaurus = CollegiateThesaurus(key)
thesaurus.lookup('umpire')
```

the shape of the result is basically the same, you can get `synonyms` & `antonyms`.

**Comment by NdYAG** [comment]
@alex-taxiera 
also please update to version `3.0.0`
If there are any problems, please let me know, thank you

**Comment by NdYAG** [comment]
Hey @alex-taxiera 
I'll close this issue, if you have any question about the new version, feel free to re-open it.
